# docker-compose.yml

services:
  postgres:
    image: postgres:15
    container_name: veri_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=verishield_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5
    container_name: veri_neo4j
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/secret123
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  backend:
    build: ./backend
    container_name: veri_backend
    depends_on:
      - postgres
      - neo4j
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env   # or remove if you don't have a .env
    # Optional volume so changes in 'backend/' appear live in the container:
    volumes:
      - ./backend:/app/backend
    # If you prefer using the Dockerfile’s CMD, remove this line:
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  postgres_data:
  neo4j_data:
